

WITH CTE AS (SELECT [MATNR],[EAN PK],[lastean], ROW_NUMBER() OVER (PARTITION BY [EAN PK] ORDER BY [EAN PK], [MATNR] DESC) row_num FROM EAN) 
Update CTE set LastEAN = 1 WHERE row_num = 1;
WITH CTE AS (SELECT [MATNR],[EAN PK],[lastean], ROW_NUMBER() OVER (PARTITION BY [EAN PK] ORDER BY [EAN PK], [MATNR] DESC) row_num FROM EAN) 
Update CTE set LastEAN = NULL WHERE row_num <> 1;
DELETE  FROM EAN where MATNR = ''
